### PR TITLE
Issues/#580 gas chart

### PR DESCRIPTION
**Pull request by grdw**
This chart has no values for gas or gas with strategies yet. These are merely the alterations needed to plot them in the graph.

### CODE REVIEW

**Comment by antw** [comment]
Sorry, haven't forgotten about this. :blush: I'm working on adding gas to the network calculation, and will merge this pull request at the same time.

**Comment by grdw** [comment]
This probably still needs some hooking up to the now existing  gas caculation? @antw

**Comment by antw** [comment]
Yes, I'm already on it. :smiley:

**Comment by grdw** [comment]
> Yes, I'm already on it

Haha, I thought I needed to make some changes to it. But are you already working on it or?

**Comment by antw** [comment]
> Haha, I thought I needed to make some changes to it.

Looks fine to me! I have pushed a commit which will show the real gas loads in the chart; could you take a look and make sure I'm not making a mess of your JavaScript? :blush: 

You might have a hard time *testing* it yourself since the space heating demand profiles haven't been set up yet. Once this is merged I'll get the whole lot (profiles included) onto the staging server.

screen shot 2015-12-10 at 16 20 40

**Comment by grdw** [comment]
It looks good to me. Except for the hacky part, but we'll clean that up later.

**Pull request merged**
