### PR TITLE
Issues/#295 persistence with local storage

### PR DESCRIPTION
**Pull request by grdw**

### CODE REVIEW

**Comment by antw** [comment]
I'm sure this was working when I tested earlier, but now whenever I view an LES the network diagram doesn't show up (`.testing-ground-view` is empty). Can you reproduce this @grdw or is it just at my end?

**Comment by grdw** [comment]
> Can you reproduce this @grdw or is it just at my end?

Yes, I messed up some rebases. It's solved now.

**Comment by grdw** [comment]
One moment please. Need to check some things first.

**Comment by grdw** [comment]
@antw It's ready to go!

**Pull request merged**
