### PR TITLE
Bump etmoses to ruby version 2.3.1

### PR DESCRIPTION
**Pull request by grdw**
I explicitly left out the `config/deploy.rb` setting due to the fact that 2.3.1 is probably not installed on the server. 

Would it be as easy as doing `rbenv install 2.3.1` on the server, updating the `config/deploy.rb` and hope everything is allright? 😆 Or would this have to be done in ansible?

### CODE REVIEW

**Comment by antw** [comment]
> I explicitly left out the config/deploy.rb setting due to the fact that 2.3.1 is probably not installed on the server.

I made my previous comment on the commit before the pull request was made; somehow it ended up in here and it looks like I didn't read your message. Sorry. :grinning:

> Would it be as easy as doing rbenv install 2.3.1 on the server, updating the config/deploy.rb and hope everything is allright? 

Yes! When the app is deployed we have to shut it down and start it back up. Normally Unicorn will do a hot-reload which would mean it uses the old version of Ruby.

**Comment by antw** [comment]
> Or would this have to be done in ansible?

This is a good point. Our [Ansible roles assume only one version per server](https://github.com/quintel/ansible/blob/049738450557427d09212279181bd97448358838/etmodel.yml#L13-L14), but there is nothing to prevent us from installing other versions manually (which I did this morning for ETEngine).

It might be possible to specify the Ansible role multiple times each with a different Ruby version, but I'm not sure about that.

**Comment by grdw** [comment]
> When the app is deployed we have to shut it down and start it back up. Normally Unicorn will do a hot-reload which would mean it uses the old version of Ruby.

So it's 

````bash
rbenv install 2.3.1
# make tea
rbenv local 2.3.1
kill -USR2 <pid-of-unicorn> ?  or run a `be cap staging deploy`?
````

**Comment by antw** [comment]
[Capistrano runs `-USR2` automatically after a deploy](https://github.com/quintel/etmoses/blob/5899df66c81b5f26cf5d11f37c2df56d6d93bf0a/config/deploy.rb#L49) and that didn't do the trick for ETEngine. I guess restarting a Ruby 2.1.1 Unicorn process will just brought up another 2.1.1 process. For ETEngine I had to shut down the app completely and start it back up again (via SSH):

```sh
sudo service etengine-staging stop
# wait a sec ...
sudo service etengine-staging start
```

You might be able to get away with doing it via Capistrano:

```sh
bundle exec capistrano staging unicorn:stop
bundle exec capistrano staging unicorn:start
```

... but if Upstart detects that the process has stopped, it could automatically bring it back up again before you get a chance to run `unicorn:start` (which is probably fine).

**Comment by grdw** [comment]
I'm currently installing ruby 2.3.1 on the beta server of ETMoses.

**Comment by ploh** [comment]
I hope I am doing this right... with just adding a commit to the branch. I did not mean to "hijack" your pull request, grdw.

**Comment by antw** [comment]
[Yesterday we discovered](https://github.com/quintel/etmoses/commit/a6645694caa99539035d1da111f7bd2658ff63f4#commitcomment-19680927) that, when executing Capistrano, `Dir.pwd` is the project root directory, so the full path isn't really required. You can't run Capistrano outside the root directory AFAIK.

Alternatively, you could get the path with a little less noise like so:

```ruby
File.expand_path('../.ruby-version', __FILE__)
```

**Comment by ploh** [comment]
> You can't run Capistrano outside the root directory AFAIK.

OK... I just tried it and it did not run in a sub-directory. So I agree with the simple version. :smile:

**Comment by ploh** [comment]
I just did the hacky thing and did a _reset_ instead of _revert_ on the branch. Did not want to clutter the history. Is that ok for small not-yet-merged branches like this one? @antw

**Comment by antw** [comment]
> Did not want to clutter the history. Is that ok for small not-yet-merged branches like this one? @antw

We do that quite a bit when we want to keep the history clean. No problem at all.

Ironically after all this discussion, when merging the  ETModel version of this I discovered that Semaphore's automatic deploy system *refuses* to read the .ruby-version file; it insists that the file doesn't exist! Didn't matter whether I used the simple version, or the full `expand_path` version, it just didn't work. Worked perfectly when I ran the deploy manually though.

I've changed them both to specify the version as a string instead of reading the file. We'll just have to be extra careful when we change the Ruby version in the future.

--

Semaphore output for `File.read('.ruby-version').strip`:

```
cap aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - .ruby-version
config/deploy.rb:11:in `read'
config/deploy.rb:11:in `<top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/setup.rb:14:in `load'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/setup.rb:14:in `block (2 levels) in <top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/bin/cap:23:in `load'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/bin/cap:23:in `<top (required)>'
Tasks: TOP => staging
(See full trace by running task with --trace)
```

Semaphore output for `File.read(File.expand_path('../../.ruby-version', __FILE__)).strip`:

```
cap aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/runner/etmodel/.ruby-version
config/deploy.rb:11:in `read'
config/deploy.rb:11:in `<top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/setup.rb:14:in `load'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/setup.rb:14:in `block (2 levels) in <top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/bin/cap:23:in `load'
/home/runner/etmodel/vendor/bundle/ruby/2.3.0/bin/cap:23:in `<top (required)>'
Tasks: TOP => staging
(See full trace by running task with --trace)
```

**Pull request merged**
