### PR TITLE
Set date select week for gas chart correctly

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #1356

### CODE REVIEW

**Comment by antw** [comment]
Maybe I'm doing something wrong, but when I load the gas chart, having selected the second week in the electricity chart, it's still loading data for the *first* week of the year (even though the date select says otherwise):

```json
{"calculation":{"range_start":0,"range_end":672,"resolution":"high"}}
```

**Comment by antw** [comment]
Whenever I select a new chart (Electricity → Gas, Heat → Electricity), it resets back to week 1. Is that by design? It's still better than labelling the data with the wrong week, so although it's a pity to lose the ability to remember which week was selected, we can merge this if it's intentional and @ChaelKruip is happy.

**Comment by ChaelKruip** [comment]
> Whenever I select a new chart (Electricity → Gas, Heat → Electricity), it resets back to week 1.

I would be happier if it would remember the week but if that is very difficult I can live with resetting.

**Comment by grdw** [comment]
>  I can live with resetting.

Fine. The normal behavior in the first place would be resetting. I'll make a separate issue for the synching.

**Pull request merged**
