### PR TITLE
Adding admin rights

### PR DESCRIPTION
**Pull request by grdw**
Merge after #377  please :smile:

### CODE REVIEW

**Comment by antw** [comment]
Merged; thanks!

**Comment by antw** [comment]
@ChaelKruip @dennisschoenmakers @jorisberkhout I changed your accounts on beta to give them admin privileges.

**Comment by ChaelKruip** [comment]
> @ChaelKruip @dennisschoenmakers @jorisberkhout I changed your accounts on beta to give them admin privileges.

:tada: :+1:

**Comment by grdw** [comment]
[Remember ... ](https://youtu.be/b23wrRfy7SM?t=12s)

**Pull request closed without merging**
