### PR TITLE
Issues/profile table select boxes

### PR DESCRIPTION
**Pull request by grdw**
Replaces the type column with a select box.

### CODE REVIEW

**Comment by grdw** [comment]
@antw if you have time to merge this. If you don't please tell, than I'll merge it myself.

**Comment by antw** [comment]
Feels like a big improvement, but the behaviour of the drop-downs is a bit awkward. The first time I click on the table cell, the select appears (and is focused) but the options don't; I have to click a second time. 

It would also be nice for the profile select to update as soon as you change the technology type – currently I find that it only changes once I unfocus the technology type select.

Maybe these are limitations of the table editor library? Would be a pity because I think it will quickly get annoying to have to double-click everything.

**Comment by grdw** [comment]
Thanks for your comments. Agree with the double-click, considering that I already made a lot of changes to the existing library, a little more changes might not hurt too much.

**Comment by grdw** [comment]
> Feels like a big improvement, but the behaviour of the drop-downs is a bit awkward. The first time I click on the table cell, the select appears (and is focused) but the options don't; I have to click a second time. 

This is currently not possible, only with some dispatch-MouseEvent-Javascript voodoo which only works in Chrome. So it's kind of a bummer (it seemed like such an easy thing to do) :disappointed: 

>It would also be nice for the profile select to update as soon as you change the technology type – currently I find that it only changes once I unfocus the technology type select.

Done :smile:

**Comment by antw** [comment]
> This is currently not possible, only with some dispatch-MouseEvent-Javascript voodoo which only works in Chrome. So it's kind of a bummer (it seemed like such an easy thing to do in the first place)

That's a shame; I think having to double-click the select box is poor user experience. However, it's still better than having to remember the names of technologies and profiles, so I think it's worth keeping.

I wonder if we could (eventually) replace the table-editor with a simpler solution where the table cells contain the form fields already, instead of being inserted dynamically by JS?

**Comment by grdw** [comment]
> I wonder if we could (eventually) replace the table-editor with a simpler solution where the table cells contain the form fields already, instead of being inserted dynamically by JS?

That would be easier. Also saves a lot of JS; I'll discuss this with @ChaelKruip

**Pull request merged**
