### PR TITLE
Setting the correct number of units for secondary heat assets

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #1586

### CODE REVIEW

**Comment by antw** [comment]
Is it possible to instead determine the number of units during the cost calculation? I thought we avoided setting a NoU attribute on heat assets since the number of heat connections could change when the user added or removed "district heat" technologies, and this wouldn't be reflected in the assets when using an explicit NoU?

**Comment by grdw** [comment]
> Is it possible to instead determine the number of units during the cost calculation? 

That's correct. I'll see what I can manage.

**Comment by grdw** [comment]
@antw I mange to include the `heat_connections` in the initial market calculation for heat assets. 👍 So no noh in the db.

**Comment by antw** [comment]
Looks good! :+1:

**Pull request merged**
