### PR TITLE
Issues/#519 calculate les bg

### PR DESCRIPTION
**Pull request by grdw**
Calculate the load in delayed job.

Fixes: #385

### CODE REVIEW

**Comment by antw** [comment]
Is this ready? There are a lot of (I think) unrelated changes, so it's hard to tell. I *think* it might need to be updated or rebased on account of the changes that were made to the caching PR; I see [some code from the original implementation](https://github.com/quintel/etmoses/commit/c472317f33ca43ed20794ba95b9f5330474978f1#diff-27a7aedba59d5f302ac9ff620caf0273R22) in this one.

**Comment by grdw** [comment]
> Is this ready?

Yes. The thing is that I originally created the branch of master when I was done with the first version of the caching. Than when the changes occured I had to do a really painful rebase with lots of conflicts. 

Now the rebasing doesn't do that much. Maybe I could remove that one commit because it doesn't add that much value for this PR.

**Comment by antw** [comment]
I tried this locally, but it's not working for me: it seems to expect a `job_id` column in `testing_grounds`, but there's no migration to create it. I'm curious if a single `job_id` column is compatible with the idea of calculating the "basic" and "feature" networks simultaneously (in separate jobs)?

**Comment by grdw** [comment]
> but there's no migration to create it. 

Crap, think I deleted that migration with the commit I removed from this PR.

**Comment by grdw** [comment]
> I'm curious if a single job_id column is compatible with the idea of calculating the "basic" and "feature" networks simultaneously

Well, yes. I was curious that it *did* work aswell. My guess is though that my local Rails environment `queues` up the two requests. 

I added the migration :+1: so you can fiddle with it.

**Comment by antw** [comment]
> My guess is though that my local Rails environment queues up the two requests.

I think so too. It might not work in a multi-process environment such as we have on staging and production. Separate `basic_job_id` and `feature_job_id` columns would do the trick, as would storing these in a separate table with `testing_ground_id`, `job_id` and `type` columns (where `type` is "basic" or "feature").

A separate table is more flexible should we ever add more "types" (for example, a low resolution version), but I doubt that will happen in the *immediate* future.

**Comment by grdw** [comment]
> as would storing these in a separate table

Did it. :smile:

**Pull request merged**
