### PR TITLE
Fixing type column for csv

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #629

### CODE REVIEW

**Comment by antw** [comment]
Same problem as #621; I get a `ctionController::InvalidAuthenticityToken` when I choose a CSV to upload and hit "save". Is it just me? :anguished:

**Comment by grdw** [comment]
> when I choose a CSV to upload and hit "save". Is it just me?

I'm having a hard time reproducing this one. Because importing a CSV file and than calling create calls to `TestingGroundsController#create as HTML` with an actual valid authenticity token as far as I know.

**Comment by antw** [comment]
> calling create calls to `create` as HTML with an actual valid authenticity token as far as I know.

Exactly! It's weird; maybe it's something in my local setup. If you know that this works, let's merge it. :+1:

**Comment by grdw** [comment]
Do you use pow? https://github.com/basecamp/pow/issues/96 

Sort of did a really quick google.

**Comment by antw** [comment]
> Do you use pow?

Yeah; restarting Pow has no effect, and the exception also gets raised when using the built-in Rails server. It's got to be something local, never mind.

**Pull request merged**
