### PR TITLE
Issues/#337 les interface restructuring

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #337 
Fixes: #352

### CODE REVIEW

**Comment by antw** [comment]
I made a couple of small visual tweaks:

* Lightened the background on selected strategies; the default dark blue was a bit overwhelming, and clashes with the OS X 10.10 checkbox colour,

* Fixed the padding in the multi-select (the bootstrap defaults were overriding the multi-select CSS styles),

* Reduced the size of the helper text beneath the solar PV slider (prevents the drop-down from growing in width when solar PV capping is enabled),

* Made the multi-select always read "Pick a strategy (__ selected)". The default behaviour was to replace the button text with the names of the chosen options, but that didn't feel right in practice since our options are so wordy.

* Moved the "Edit" button to the right, away from the title (and added an icon to draw attention to it).

screen shot 2015-09-08 at 12 32 57

What do you think?

Two other things stand out to me:

* boostrap-multiselect has a `includeSelectAllOption` which would be a good usability improvement for when you want to turn on all strategies at once. I tried to add this, but it didn't work as expected in our app. It would select all options, but the "Select all" checkbox would remain unticked, and I couldn't click it again to deselect all the strategies. Not a big loss if we can't use it, but it would be nice.

* [Currency formatting in the business case table](https://github.com/quintel/etmoses/pull/351/files#diff-6c6f6d2aeeec8f74c8dd28011f1bd5e4R5) seems to be in the decimal-comma style ("€5.000,00") rather than decimal-point ("€5,000.00"). Was this intentional? I only ask because other numbers in the app – and currency figures in other applications (ETM) – use the decimal-point style.

  My understanding is decimal-point is standard in scientific use, but perhaps @ChaelKruip can shed some more light on this. Maybe decimal-comma *is* used in non-English papers? I'm fine with using decimal-comma if we're focusing on an EU-only audience, but I think it has to be applied consistently to all numbers, not just one table.

Otherwise, I'm really happy with this and can't wait to get it merged. :+1:

**Comment by grdw** [comment]
> What do you think?

That looks good! :+1: 

> Two other things stand out to me:

> bootstrap-multiselect has a includeSelectAllOption 

Yes, I'll fiddle with it. 
 
> Currency formatting in the business case table seems to be in the decimal-comma style ("€5.000,00") rather than decimal-point ("€5,000.00"). Was this intentional? 

No, it isn't, but if decimal-point is the default I'll change it to decimal-point.

**Comment by ChaelKruip** [comment]
Excellent work guys! This looks sooo much better than before. 

> No, it isn't, but if decimal-point is the default I'll change it to decimal-point.

Decimal point makes more sense to me as well as it is consistent with the rest of the ETM. Well spotted @antw!

**Comment by grdw** [comment]
> Yes, I'll fiddle with it. 

I fiddeled, but I'm guessing this is the type of "I'll fix this in 5 minutes, 8 days later it still isn't solved" -type of issue.

So I'll make an issue of it for a later moment in time. I have no idea why it isn't working properly.

**Comment by antw** [comment]
> I fiddeled with the includeSelectAllOption, but I'm guessing this is the type of "I'll fix this in 5 minutes, 8 days later it still isn't solved" -type of issue.

I know the feeling. :anguished:

One merge coming up!

**Comment by grdw** [comment]
> I made a couple of small visual tweaks:

@antw  are these visual tweaks also merged or?

**Comment by antw** [comment]
Oops. I didn't push them to your branch. :blush: 

I'll fix it now, sorry!

**Pull request merged**
