### PR TITLE
Issues/#508 storing existing load calculation

### PR DESCRIPTION
**Pull request by grdw**
Implements a basic caching system which is the following:

- Caches the load calculation
- Clears the cache once the strategies are changed or when the topology / market model / technologies are in any way changed

This merge request also contains the following:
- Increase speed for removing the green line
- Only submit forms that have been edited when clicking 'Save all' - instead of submitting each form.
- Fixes: #514, #508

### CODE REVIEW

**Comment by grdw** [comment]
@antw I fixed your comments :+1:

**Comment by antw** [comment]
The main issue to be solved is the way caching bleeds across several layers of the application. Discussed in "[Transparent caching](https://gist.github.com/antw/11575308b15db05b75de#transparent-caching)", neither the front-end nor the network calculation *process* should be involved in caching. This means:

1. The `clear_cache` parameter should not be needed by the JS in order to expire the cache.
2. The `Network` and `Calculation` classes [should not be writing the cache](https://github.com/quintel/etmoses/commit/6a703fc23cebbbdf9125a42dc884e799e4488463#diff-27a7aedba59d5f302ac9ff620caf0273R22).

#### Suggestions:

1. Have the Rails controllers or [models expire the cache](https://gist.github.com/antw/11575308b15db05b75de#expiring-when-updated) instead of using a `clear_cache` parameter.
2. Instead of using `NetworkCache::Writer` in `Calculation::PullConsumption`, write to the cache *after* calling `TestingGround#to_calculated_graph`.

  For example:
  
  ```ruby
  class TestingGroundController
    def data
      network = if NetworkCache.present?(testing_ground)
        # The network has a cache stored on disk. Load network from cache.
        NetworkCache.write(...)
      else
        # Network is not cached. Calculate it, then cache the results.
        network = testing_ground.to_calculated_graph
        
        # Write cache, then...
        NetworkCache.write(network, ...)
        
        network
      end
      
      respond_with network
    end
  end
  ```
  
  This could probably be simplified as:
  
  ```ruby
  class TestingGroundController
    def data
      respond_with(NetworkCache.fetch(testing_ground, opts) do
        testing_ground.to_calculated_graph(opts)
      end)
    end
  end
  
  module NetworkCache
    module_function
    
    # Reads the cache if present. If not (read returned nil) the block is executed
    # and the cache is written.
    def fetch(testing_ground, opts = {}, &block)
      read(testing_ground, opts) || write(testing_ground, opts, &block)
    end
    
    def read(testing_ground, opts = {})
      if present?(testing_ground, opts)
        # Read from cache.
      end
    end
    
    def write(testing_ground, opts, &block)
      # Remove existing cache if present, then...
      Writer.from(testing_ground, opts).write!(block.call)
    end
  end
  ```

**Comment by grdw** [comment]
> Discussed in "Transparent caching"

It's not really much of discussion, but I get the point. Thanks for explaining. :+1: 

Will change this.

**Comment by antw** [comment]
> It's not really much of discussion

discuss
* talk about (something) with a person or people.
* *talk or write about (a topic) in detail, taking into account different issues or ideas.*

I was going for the second meaning. :smiley:

> Thanks for explaining. :+1: Will change this.

The rest of the ideas in document can wait, at this stage they're "nice-to-have" rather than essential. Getting caching out of the front-end and `Network`/`Calculation` is the only thing we *need* to do, as I could see that causing us problems whenever we make changes to either. If that can be solved, we'll merge this and can revisit at a later date.

**Comment by grdw** [comment]
@antw I managed to remove the caching from the load calculation and from the front end.

That's what I managed to do. What I didn't manage to do yet is the refactoring of the `Reader` and `Writer`. Like what you said, the `Reader` only contains one usable line.

Before I'm going to do that I want you to look at the current code and sort of say whether the direction this is going in, is any good.

**Comment by antw** [comment]
> Before I'm going to do that I want you to look at the current code and sort of say whether the direction this is going in, is any good.

Looks like a *big* improvement. Refactoring `Reader` and `Writer` isn't strictly necessary, but it would be nice *if* you have the time available to do so. If not, I can start doing some testing as soon as you want.

**Comment by grdw** [comment]
> but it would be nice if you have the time available to do so

That's the issue sort of. I was supposed to already start with the importing of Gas technologies. Which is now a little delayed. :sweat_smile:  I'll leave this for now and see if on the train ride home I can make some refactoring thingies.

**Comment by grdw** [comment]
I did manage to refactor some things. Still would like to read up on the whole facade pattern (or any other cool patterns) before actually using it. Otherwise I'll just be copying and pasting your suggested code, which is something I won't learn that much from.

**Comment by antw** [comment]
This looks pretty good to me. I did manage to find a way to break it, however: if you edit a topology on the "edit topology" page (`TopologiesController#edit`), the cache for affected networks doesn't get cleared.

**Comment by grdw** [comment]
> if you edit a topology on the "edit topology" page (TopologiesController#edit), the cache for affected networks doesn't get cleared.

Yes. I might have a question about that, now that you mention it.

The `TestingGround::Cloner` class also destroys the cache. But would that be - according to [Transparent Caching](https://gist.github.com/antw/11575308b15db05b75de#transparent-caching) - a 
good practise? 

The easy way to Rome right now would be, is to expand the `update` method in the `TopologiesController`

````ruby
def update
  testing_ground = TestingGround.find(session[:testing_ground_id])
  NetworkCache::Destroyer.from(testing_ground).destroy_all
  
  @topology.update_attributes(topology_params)
  respond_with(@topology)
end
````

Which results in this heap of code. And I'm not sure if a controller should be aware of the caching?

**Comment by antw** [comment]
> The easy way to Rome right now would be, is to expand the update method in the TopologiesController

Pulling the testing ground out of the session isn't enough as there may be many using the same topology. I guess you'd have to:

```ruby
TestingGround.where(topology_id: topology.id).find_each do |tg|
  NetworkCache::Destroyer.from(tg).destroy_all
end
```

> The TestingGround::Cloner class also destroys the cache. But would that be - according to Transparent Caching - a good practise?

... I get the sense that you feel this is *not* a good practice; I agree. If time is limited, I'd say this is an acceptable compromise given that [something similar already happens in the TestingGround controlle](https://github.com/quintel/etmoses/blob/4644d1961c5165d15e71f03654bb3bb56159b80a/app/controllers/testing_grounds_controller.rb#L113).

The ideal solution is for the `NetworkCache` to determine if the cache is fresh (valid) or has expired based on the TestingGround it is given. This way, the Rails layer (the controllers, models, `Cloner`, etc) never need to know anything about the cache.

You'd need to save some metadata with the cache – namely the time at which the cache was written – and every time you read the cache check if any of the models have been updated. If their `updated_at` is *after* the cache was written, the cache is invalid, should be deleted and rewritten.

* For the "basic" graph, if the TestingGround or Topology `updated_at` is after the cache creation time, then the cache has expired.
* For the "feature" graph, if the TestingGround, Topology, or SelectedStrategy `updated_at` is after the cache creation time, then the cache has expired.

Perhaps that can probably accomplished somewhere in [`NetworkCache::Validator#valid?`](https://github.com/quintel/etmoses/blob/4644d1961c5165d15e71f03654bb3bb56159b80a/app/services/network_cache/validator.rb#L3-L5)

```ruby
def valid?
  cache_intact? && identical_strategies? && fresh?
end

private

def fresh?
  times = [
    testing_ground.updated_at,
    testing_ground.topology.updated_at,
    testing_ground.selected_strategy.updated_at
  ].max

  cache_created_at > times
end
```

--

Some other observerations:

* Why do `Fetcher`, `Destroyer`, `Validator`, etc, all inherit from `Cache`? I'm guessing it's because they all need [the same initialize method](https://github.com/quintel/etmoses/blob/4644d1961c5165d15e71f03654bb3bb56159b80a/app/services/network_cache/cache.rb#L7-L10)? If so, put it into a module and then `include` it into each class.

* Ideally, TestingGround::Calculator [should not write a SelectedStrategy](https://github.com/quintel/etmoses/blob/4644d1961c5165d15e71f03654bb3bb56159b80a/app/services/testing_ground/calculator.rb#L28) if one does not exist. This makes it not transparent as the presence of the cache has an effect on the database which would not happen if the cache were not there. (I think I'm realising that by "transparent" what I really mean is: "caching should have no side-effects on the rest of the application").

**Comment by grdw** [comment]
> Perhaps that can probably accomplished somewhere in

Thanks! Implemented it by using the oldest `mtime` method (it grabs the oldest modification time for a cache file) and compare it against the updated at for the les and associated topology and market model.

> Why do Fetcher, Destroyer, Validator, etc, all inherit from Cache? I'm guessing it's because they all need the same initialize method? 

Yes and most of the private methods in `Cache`. But okay.

> Ideally, TestingGround::Calculator should not write a SelectedStrategy if one does not exist. 

How would that ideally look like? One global class which calls the `Calculator` and the `StrategyUpdater` separately?

**Comment by antw** [comment]
> Yes and most of the private methods in `Cache`. But okay.

I'm not meaning to be difficult, I hope you know that. :scream:  

It's just that subclasses should have an "is-a" relationship with the superclass. `Dog` is an `Animal`. `Phone` is a `Device`. Any place you'd use an `Animal`, you should be able to substitute a `Dog` without anything breaking (this is "[polymorphism](https://en.wikipedia.org/wiki/Polymorphism_(computer_science)#Subtyping)" or "[duck typing](https://en.wikipedia.org/wiki/Duck_typing)").

But, as far as I could tell, a `Validator` isn't a `Cache`. In those cases, a shared module is clearer.

> How would that ideally look like? One global class which calls the Calculator and the StrategyUpdater separately?

I think if you write the SelectedStrategy (with all the strategies off?) when the TestingGround is created, the problem is solved. Updating the SelectedStrategy is probably the responsibility of the controller.

**Comment by grdw** [comment]
> I'm not meaning to be difficult, I hope you know that. 

I know. I just wanted to know why. :smile:  Thanks for explaining!

Maybe my cold was talking here.

> I think if you write the SelectedStrategy (with all the strategies off?) when the TestingGround is created

Yes,

> Updating the SelectedStrategy is probably the responsibility of the controller.

Not necessarily would be my reaction. But I'll see if there's some nicer way.

**Comment by grdw** [comment]
Not to self:
I'll keep the `around_filter`. When this is merged and when the background-calculation pull request will re-appear. I shall remove the `after_filter` and put it in the `success` method of the `Delayed::Job`.

**Comment by grdw** [comment]
@antw is that 'okay' with you? I will create the other pull request as soon as this one is merged.

**Comment by antw** [comment]
> I think if you write the SelectedStrategy (with all the strategies off?) when the TestingGround is created

I think something may have gone awry here. I tried to load a couple of testing grounds locally, and they all initially showed that no strategies were turned on. When I selected a strategy, the following exception gets raised (I guess because there's no `SelectedStrategy` for the LES?).

--

##### NoMethodError at /testing_grounds/351/data.json

> undefined method `update_attributes' for nil:NilClass

##### app/controllers/testing_grounds_controller.rb, line 205

``` ruby
  200       authorize @testing_ground
  201     end
  202   
  203     def update_strategies
  204       if params[:strategies]
> 205         @testing_ground.selected_strategy.update_attributes(strategy_params)
  206       end
  207     end
  208   
  209     # Internal: Before filter which loads models required for export-to-ETEngine
  210     # eactions.
```

--

I think it's because the app now expects a SelectedStrategy to be created when the TestingGround is ([here](https://github.com/quintel/etmoses/pull/518/files#diff-c2b7ca637ffbb6e651981cf3b6d89d2aR65)), but then breaks when an using an older LES which doesn't have a SelectedStrategy. This could be fixed by a migration to add a SelectedStrategy to each LES which doesn't already have one.

Otherwise, this pull request looks good. :+1:

**Comment by grdw** [comment]
> This could be fixed by a migration to add a SelectedStrategy to each LES which doesn't already have one.

Yes. That's the case. I'll create a migration for it.

**Comment by grdw** [comment]
@antw I added the pull request :smile:

**Comment by grdw** [comment]
@antw I added the migration :smile:

**Comment by antw** [comment]
Yes! Looks good! Thanks for the work; and for your patience with all of my requests. :laughing: 

Gonna merge this now. :+1:

**Comment by grdw** [comment]
> and for your patience with all of my requests.

Haha, no problem. I learned a lot! So thanks.

**Pull request merged**
