### PR TITLE
Updated ETMoses welcome text; closes #495

### LINKED ISSUE #495: ETMoses landing page should advertise our workshops
John pointed out that because ETMoses is a real experts-tool it would be good to if he user would find his way to a workshop about how to use ETMoses rather than him getting frustrated by reading a lot of complex documentation.

### PR DESCRIPTION
**Pull request by jorisberkhout**
Assigning @ChaelKruip to review the new text. Before he does so, could you check if this works technically, @grdw ? I can't get ETMoses to run locally, so I cannot verify if the syntax is correct. Please push any fixes to this branch.

### CODE REVIEW

**Comment by grdw** [comment]
screen shot 2016-05-31 at 10 44 16

This is what it looks like from here. It might need a bit more breaks here and there.

**Comment by ChaelKruip** [comment]
I have made some changes. Please have a look @dennisschoenmakers and merge if satisfied:
slack

**Comment by grdw** [comment]
Well, I agree what's being written but I don't really like how it looks. Maybe the text should be more in line with the "Getting started" text? I can't really pin-point it but it doesn't look right from a distance.

**Comment by antw** [comment]
> Maybe the text should be more in line with the "Getting started" text? I can't really pin-point it but it doesn't look right from a distance.

Looks like the Moses logo is too far to the left. It should be aligned with the introductory text, and the grey box with the "Getting started" info. Apparently that's a Bootstrap thing, but I'm not sure why...

```css
.navbar > .container .navbar-brand, .navbar > .container-fluid .navbar-brand {
    margin-left: -15px;
}
```

Other than that, [the line length is way too long](http://webtypography.net/2.1.2), which makes it hard to read.

**Comment by ChaelKruip** [comment]
> Well, I agree what's being written but I don't really like how it looks. Maybe the text should be more in line with the "Getting started" text? I can't really pin-point it but it doesn't look right from a distance.

Only after @antw's comment did I realise that you are talking about the layout. I thought you were commenting very poetically about the content of the text. 😆

**Comment by grdw** [comment]
>  I thought you were commenting very poetically  about the content of the text. 

The text is written by someone very wise
The layout however is not so nice

- Gerard, 2016

**Comment by jorisberkhout** [comment]
This commit is merged in the `master` branch, but I don't see it when I go to https://moses.energytransitionmodel.com/welcome. Any suggestions on why this is not shown, @grdw ?

**Comment by antw** [comment]
master = staging / beta
production = production

A number of bug fixes have been applied to production, but minor stuff like this (and the heat network) are still only on beta.

**Pull request merged**
