### PR TITLE
Issues/concurrency split

### PR DESCRIPTION
**Pull request by antw**
Reopened version of #1277 due to #1321.

> What this pull request is and what is isn't:
> 
> *What it is:*
> A basic setup of the technology splitter as described in: #1267. It splits a technology in groups of 2. The code however is build in a way that it can split into groups [larger than 2](https://github.com/quintel/etmoses/pull/1277/files#diff-b32f238bbcae4cdd5ef98a07b151e748R73) however there's currently not yet an interface available to do this. This pull request also contains lots of removal of the old concurrency code. The code also is able to split buffers and their children. The children of buffers have no units as described [here](https://github.com/quintel/etmoses/issues/1285#issuecomment-233363883).
> 
> *What it isn't:*
> The splitter doesn't automatically selects new profiles for the cloned templates. @ChaelKruip and I decided not to do this since the behavior (when cloning) is not how we expected it to be.

----

Fixes: #993, #998, #999, #1120, #1145, #1203, #1368, #1379, #1382

### CODE REVIEW

**Comment by grdw** [comment]
Waiting to fix #1368 before merging this. Will commit the result in this same PR.

**Comment by antw** [comment]
I gave this a spin, and the "split" feature and HHP both seem to work nicely.

However I'm concerned about how we will deal with existing LESes. For example, if you have a buffer in a LES like this:

* Space heating buffer – Units: 100
  * Heat pump (air) – Units: 30
  * Electric heater – Units: 70

... and then re-save the LES, you end up with:

* Space heating buffer – Units: 100
  * Heat pump (air) – Units: 100
  * Electric heater – Units: 100

A newly-imported LES would of course have two separate buffers:

* Space heating buffer 1 – Units: 30
  * Heat pump (air)
* Space heating buffer 2 – Units: 70
  * Electric heater

--

I think we might need to add a migration to convert old LESes to the new way of doing things, otherwise costs and loads are going to be dramatically different.

**Comment by grdw** [comment]
> I think we might need to add a migration to convert old LESes to the new way of doing things, otherwise costs and loads are going to be dramatically different.

Yes. So in fact; grab every child/technology from every buffer. Create a new buffer with the units of the child/technology and attach it to the child/technology.

**Comment by grdw** [comment]
I've managed to write a migration for all the old LES's [here](https://github.com/quintel/etmoses/pull/1322/files#diff-221897ffc2140123e1acf5e9b383d3d1R1) 👍 

@antw If you could try it out.

**Comment by antw** [comment]
I pushed a change to the migration to ensure each buffer got a unique index (otherwise it was starting at "1" for each endpoint; it could result in several "buffer_space_heating_1" in a LES). Otherwise, the code looks fine and the new features work as expected. :+1:

I'm holding off on merging (briefly) while I check out differences in heat demand and supply between `master` and this branch:

| Branch | Chart |
| :-: | --- |
| master | screen shot 2016-08-23 at 12 18 11 |
| PR | screen shot 2016-08-23 at 12 18 05 |

This is a default NL/2050 scenario. I'm a bit bothered by the deficit (which seems proportional to demand) and the *almost* total absence of buffering. Once I've managed to explain these two things, and I'm sure they're not caused by a bug in the calculation, I'll merge the pull request.

**Comment by antw** [comment]
### Deficit

The deficit is caused by a buffer whose technology is a district heat connection. The default scenario has no dispatchable central heat production, and must-runs were being imported without being assigned a number of units or a profile. 😕 

[I have resolved this](https://github.com/quintel/etmoses/commit/9233b00290ba5612eb5efa9f4f016d1596e933db); any deficit which still exists in the default scenario is due to insufficient supply from the central heat network.

### Lack of buffering

In the original scenario there is no excess PV, therefore heat is buffered by heat pumps only. A single heat pump was connected to a buffer with a myriad of other technologies. That buffer had a volume of 2.9065kWh and 34 units, for a total volume of slightly under 100kWh. The heat pump therefore runs for a long time to fill up the buffer.

In the new scenario, the heat pump is connected to a buffer with only 1 unit. Therefore it fills the buffer up much sooner, and then turns off. Therefore, I think the lack of buffering is correct.

**Comment by grdw** [comment]
Does this need to any action from me before this can be merged?

**Comment by antw** [comment]
Thanks @grdw! I merged this since I think the buffering behaviour is correct.

**Pull request merged**
